# frozen_string_literal: true

source 'https://rubygems.org'

gem 'aws-sdk-dynamodb'
gem 'geocoder'
gem 'maxminddb'
gem 'pusher'

group :development, :test do
  gem 'debug'
  gem 'dotenv-rails'
  gem 'rspec'
end
