name: Deploy Ruby Lambda Staging

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kinesis-to-pusher-lambda

    env:
      LAMBDA_NAME: kinesis-to-pusher-staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"

      - name: Install dependencies
        run: |
          if [ -f Gemfile ]; then
            bundle config set path vendor/bundle
            bundle install
          fi

      - name: Zip Lambda
        run: |
          zip -r ./lambda.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.LAMBDA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.LAMBDA_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-session-name: lambda-deploy-staging

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name "$LAMBDA_NAME" \
            --zip-file fileb://lambda.zip