name: Run Rspec

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kinesis-to-pusher-lambda

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: './kinesis-to-pusher-lambda'
          ruby-version: '4.0'
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec